((magit-blame
  ("-w"))
 (magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  (\.\.\.)
  ("--no-ext-diff"))
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-file-dispatch nil)
 (magit-log
  (\.\.\.)
  ("-n256" "--graph" "--decorate"))
 (magit-merge nil)
 (magit-patch nil)
 (magit-patch-apply nil)
 (magit-patch-create nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-stash nil)
 (magit-status-jump nil)
 (magit-submodule nil
		  ("--force"))
 (magit-svn nil)
 (magit-tag nil))
